spring:
  config.active.on-profile: development
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: example
  kafka:
    bootstrap-servers:
      - localhost:9092
    properties:
      schema.registry.url: http://localhost:8081
      specific.avro.reader: true
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
logging:
  level.org.example: DEBUG
---
spring:
  config.active.on-profile: production
